debug: true
logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        web:
          client.RestTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

server:
  port: ${SERVER_PORT}

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: profiles-service
          uri: ${PROFILES_SERVICE_URL}
          predicates:
            - Path=/api/v1/profiles/**
        - id: rental-requests-service
          uri: ${RENTAL_REQUEST_SERVICE_URL}
          predicates:
            - Path=/api/v1/rental-requests/**
        - id: user-info-service
          uri: ${USER_INFO_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/auth/**
        - id: vehicle-info-service
          uri: ${VEHICLE_INFO_SERVICE_URL}
          predicates:
            - Path=/api/v1/vehicles/**